### ISSUE TITLE
Invalid model after changing a Metabolite id in the reaction mask

### ISSUE THREAD

**Issue by sthiele** [klamt-lab/cnapy#148]
First the compartment is Null. -> Error while saving
```
Traceback (most recent call last):
  File "/home/sthiele/Projects/cnapy/cnapy/gui_elements/mainwindow.py", line 659, in save_project
    self.appdata.project.cobra_py_model, tmp_dir + "model.sbml")
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/cobra/io/sbml.py", line 964, in write_sbml_model
    doc = _model_to_sbml(cobra_model, f_replace=f_replace, **kwargs)
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/cobra/io/sbml.py", line 1114, in _model_to_sbml
    specie.setCompartment(metabolite.compartment)
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/libsbml/__init__.py", line 25783, in setCompartment
    return _libsbml.Species_setCompartment(self, sid)
ValueError: invalid null reference in method 'Species_setCompartment', argument 2 of type 'std::string const &'
```
If a new compartment is set for metabolite then the saving works but we get an error on loading the model.
```
Traceback (most recent call last):
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/cobra/io/sbml.py", line 251, in read_sbml_model
    return _sbml_to_model(doc, number=number, f_replace=f_replace, **kwargs)
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/cobra/io/sbml.py", line 436, in _sbml_to_model
    cid = _check_required(compartment, compartment.getIdAttribute(), "id")
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/cobra/io/sbml.py", line 1367, in _check_required
    raise CobraSBMLError(msg)
cobra.io.sbml.CobraSBMLError: Required attribute 'id' cannot be found or parsed in '<Compartment>'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sthiele/Projects/cnapy/cnapy/gui_elements/mainwindow.py", line 619, in open_project
    temp_dir.name + "/model.sbml")
  File "/home/sthiele/miniconda3/envs/cnapy/lib/python3.7/site-packages/cobra/io/sbml.py", line 265, in read_sbml_model
    raise_from(cobra_error, original_error)
  File "<string>", line 3, in raise_from
cobra.io.sbml.CobraSBMLError: Something went wrong reading the SBML model. Most likely the SBML model is not valid. Please check that your model is valid using the `cobra.io.sbml.validate_sbml_model` function or via the online validator at http://sbml.org/validator .
	`(model, errors) = validate_sbml_model(filename)`
If the model is valid and cannot be read please open an issue at https://github.com/opencobra/cobrapy/issues .
```

**Comment by axelvonkamp** [comment]
I guess the metabolite must be associated with an existing compartment. If it is in a new compartment that compartment perhaps needs to be added explicitly to the model.

**Comment by sthiele** [comment]
Looks like this is a known issue with cobrapy. As a work around we could check for Null and unknown compartments.
For unknown compartments we could just add the compartment. But what would be the expected behavior for Null?

**Comment by axelvonkamp** [comment]
As long as SBML is the default model format we probably have to enforce that for every metabolite a comparmtment is defined.

**Comment by sthiele** [comment]
For now I introduce an "undefined_compartment_please_fix" and Issue Warning if no compartment is defined.
